# Generated by Django 4.2 on 2023-04-20 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MenuSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0)),
                ('cost', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('barcode', models.TextField()),
                ('expiration_date', models.DateTimeField()),
                ('categories', models.ForeignKey(default='카테고리가 없습니다.', on_delete=django.db.models.deletion.SET_DEFAULT, to='menus.category')),
                ('size', models.ForeignKey(default='사이즈를 선택하세요.', on_delete=django.db.models.deletion.SET_DEFAULT, to='menus.menusize')),
            ],
        ),
    ]
